### ISSUE TITLE
if __name__ ==... causes error

### ISSUE THREAD

**Issue by OevreFlataeker** [ioncodes/idacode#14]
If the python script to debug contains something like

```
if __name__ == '__main__':
    main()
```

the script will not run correctly. To fix, remove the "if" line and just directly call main().

**Comment by ioncodes** [comment]
I believe IDA sets `__name__` to its own custom thing. Can you let us know what `__name__` contains?

**Comment by OevreFlataeker** [comment]
Hm, if I am not mistaken... __name__ gives "builtins" in the VS Code Terminal when breaking on that line...

**Comment by ioncodes** [comment]
Interesting! Well, it's not really an issue specific to IDACode so a possible fix would be to just not deal with `if __name__ == ...` source lines or the other would be to override the global to `__main__`. Not sure which "fix" would suit best in this scenario.

**Comment by puppywang** [comment]
idaapi.IDAPython_ExecScript called python's exec_script, which just load all code into current context, so `__builtin__` is returned instead of `__main__`, detail information is listed here: https://stackoverflow.com/questions/711066/calling-execfile-in-custom-namespace-executes-code-in-builtin-namespace

**Comment by OevreFlataeker** [comment]
And it means it is something that would need a change in IDA or how IDA calls the script, correct? Like the last post said: Use __import__() instead of execfile()

**Comment by ioncodes** [comment]
I would assume that setting `__name__` when passing the globals into `execute_sync` should fix the issue, I will give that a shot.

**Comment by ioncodes** [comment]
I can confirm this does indeed work and doesn't cause any unexpected issues.  
![image](https://user-images.githubusercontent.com/18533297/89924912-f663c380-dc02-11ea-8c7e-14ec9e949d90.png)

**Comment by ioncodes** [comment]
I introduced `__name__` as `__main__` in the following commit: https://github.com/ioncodes/idacode/commit/6c01131296e0ca2c20224d2978750b077a3b007c. A new version will be published in the next hour.

**Comment by OevreFlataeker** [comment]
That's awesome! Thanks!
