### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by avalon1337** [ioncodes/idacode#15]
Does this only work for IDA 7.4?

**Comment by ioncodes** [comment]
IDACode was tested on IDA 7.2 - 7.4 with both Python 2 and Python 3. According to other sources it also works on 7.5 with Python 3.8 (see https://github.com/ioncodes/idacode/pull/13).

Are you having issues on a specific IDA version?

**Comment by avalon1337** [comment]
Good! 👍
