### ISSUE TITLE
Unable to attach debugger after debugpy 1.0.0 release

### ISSUE THREAD

**Issue by ViRb3** [ioncodes/idacode#19]
Something has changed between debugpy 1.0.0rc2 and 1.0.0, because on the latter I get the following error every time I try to attach the debugger from VSCode:
```
Can't find input file 'C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\debugpy\adapter'
```

Workaround:
```
pip install --user debugpy===1.0.0rc2
```

**Comment by ioncodes** [comment]
Need to check what they changed in the new version. Will fix it by forcing the rc2 version for now

**Comment by ioncodes** [comment]
Should work with the latest released version.
