### ISSUE TITLE
Imported module not updated

### ISSUE THREAD

**Issue by Xartrick** [ioncodes/idacode#36]
## Description

Imported modules do not reload when edited, keeping changes from being applied to main script.

## How to reproduce

1. Create `imported_module.py`
```python
def call_me():
    return 'Foo'
```

2. Create `main.py`
```python
from imported_module import call_me

print(call_me())
```

3. Start IDACode from IDA
```
[IDACode] Listening on 127.0.0.1:7065
```

4. Connect IDACode from VSCode
```
[IDACode] Client connected
[IDACode] Set workspace folder to c:\ida_code_bug
```

5. Save `main.py` to trigger code execution
```
[IDACode] Executing c:\ida_code_bug\main.py
Foo
```

6. Edit `call_me` in `imported_module.py` to return `Bar`
```python
def call_me():
    return 'Bar'
```

```
[IDACode] Executing c:\ida_code_bug\imported_module.py
```

7. Save `main.py` to trigger code execution
```
[IDACode] Executing c:\ida_code_bug\main.py
Foo
```

## Expected result

`call_me` function should returns `Bar`.

## Related issues

* #34

**Comment by Xartrick** [comment]
After more digging, this seems to be a known behavior, see [Loading your own modules from your IDAPython scripts with idaapi.require() – Hex Rays](https://hex-rays.com/blog/loading-your-own-modules-from-your-idapython-scripts-with-idaapi-require/).

## Solution

```python
from idaapi import require
require('imported_module')

from imported_module import call_me

print(call_me())
```

This can be closed or kept open for future reference.

**Comment by ioncodes** [comment]
Thanks for letting me know! I'll reference this issue in the README!
